
server:
  port: 8082

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: board-search-service
#  kafka:
#    consumer:
#      bootstrap-servers: 10.10.10.200:9092

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${MASTER_URL}
    username: ${MASTER}
    password: ${MASTER_PW}

    slaves:
      slave1:
        name: slave1
        driver-class-name: org.mariadb.jdbc.Driver
        url: ${SLAVE_URL}
        username: ${SLAVE}
        password: ${SLAVE_PW}

  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true
    show-sql: true
