version: '3'
services:
  mysql:
    image: mariadb:latest
    ports:
      - "3306:3306"
    volumes:
      - db-vol:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: qwer1234
      MARIADB_DATABASE: bootshelf
      TZ: Asia/Seoul

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-vol:/data

volumes:
  db-vol:
    driver: local
  redis-vol:
    driver: local
