server:
  port: 9999

spring:
  application:
    name: BOOTSHELF-GATEWAY-SERVICE
  cloud:
    gateway:

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"

      routes:
        - id: BOOTSHELF-BOARD-SEARCH-SERVICE
          uri: lb://BOOTSHELF-BOARD-SEARCH-SERVICE
          predicates:
            - Path=/board/**

        - id: review-search-service
          uri: lb://BOOTSHELF-REVIEW-SEARCH-SERVICE
          predicates:
            - Path=/review/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka