apiVersion: v1
kind: Service
metadata:
  name: mariadb-service-read
  labels:
    app: mariadb
    readonly: "true"
spec:
  ports:
  - port: 3306
    name: mariadb-port
  selector:
    app: mariadb
    role: slave