apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv-volume
  labels:
    type: local
spec:
  storageClassName: db-storage-class
  capacity:
    storage: 50Gi 
  accessModes:
    - ReadWriteOnce 
  hostPath:
    path: "/data/k8s/db/" 