apiVersion: apps/v1
kind: Deployment

metadata:
  name: board-deployment

spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 1
  minReadySeconds: 10
  selector:
    matchLabels:
      type: board
  template:
    metadata:
      labels:
        type: board
    spec:
      containers:
        - name: backend-container
          image: hyungdoyou/bootshelf-board:2.VERSION
          resources:
            requests:
              memory: "512Mi"
              cpu: "100m"
            limits:
              memory: "3Gi"
              cpu: "2000m"
          envFrom:
            - configMapRef:
                name: board-config
      terminationGracePeriodSeconds: 5