server:
  port: 8082

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: BOOTSHELF-REVIEW-SEARCH-SERVICE
  data:
    elasticsearch:
      repositories:
        enabled: true
      url: ${ES_URL}
